import type { Metadata } from 'next'
import './globals.css'
import Link from 'next/link'
import style from './layout.module.css'
import { BookData } from '@/types'

export const metadata: Metadata = {
  title: 'Bite Books',
  description: 'Generated by create next app',
}

async function Footer() {
  const response = await fetch(
    `${process.env.NEXT_PUBLIC_API_SERVER_URL}/book`,
    { cache: 'force-cache' }
  )

  if (!response.ok) {
    return <div>제작 @Jade</div>
  }

  const books: BookData[] = await response.json()
  const bookCount = books.length

  return (
    <footer>
      <div>제작 @JADE</div>
      <div>{bookCount}개의 도서가 등록되어 있습니다.</div>
    </footer>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <div className={style.container}>
          <header>
            <Link href={'/'}>📚 BITE BOOKS</Link>
          </header>
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
